// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqajxxevifmhdjlvqhkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxYWp4eGV2aWZtaGRqbHZxaGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Mzk3MzIsImV4cCI6MjA2NTQxNTczMn0.60qOLNRZJYSsVOFNoW73BULe7vHqiFz1VxD2Z243qWs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);